export type CloudTransport = "openai" | "gemini" | "anthropic";

export interface CloudProviderPreset {
  id: string;
  name: string;
  group: "国际主流" | "中国大陆" | "聚合平台" | "高速推理" | "自定义";
  transport: CloudTransport;
  baseUrl: string;
  modelHint: string;
  supportsModelList: boolean;
  note?: string;
  fallbackModels?: string[];
}

export const CLOUD_PROVIDER_PRESETS: CloudProviderPreset[] = [
  {
    id: "openai",
    name: "OpenAI",
    group: "国际主流",
    transport: "openai",
    baseUrl: "https://api.openai.com/v1",
    modelHint: "输入或读取当前账号可用的 GPT / o 系列模型",
    supportsModelList: true,
  },
  {
    id: "anthropic",
    name: "Anthropic Claude",
    group: "国际主流",
    transport: "anthropic",
    baseUrl: "https://api.anthropic.com",
    modelHint: "例如 claude-sonnet-5",
    supportsModelList: true,
    fallbackModels: [
      "claude-fable-5",
      "claude-opus-5",
      "claude-opus-4-8",
      "claude-opus-4-7",
      "claude-opus-4-6",
      "claude-opus-4-5-20251101",
      "claude-sonnet-5",
      "claude-sonnet-4-6",
      "claude-sonnet-4-5-20250929",
      "claude-haiku-4-5-20251001",
    ],
  },
  {
    id: "gemini",
    name: "Google Gemini",
    group: "国际主流",
    transport: "gemini",
    baseUrl: "https://generativelanguage.googleapis.com",
    modelHint: "例如 gemini-3.8-flash",
    supportsModelList: true,
    fallbackModels: [
      "gemini-3.8-flash",
      "gemini-3.7-flash",
      "gemini-3.6-flash",
      "gemini-3.5-flash",
      "gemini-3.5-flash-lite",
      "gemini-3.1-pro-preview",
      "gemini-3.1-flash-lite",
      "gemini-2.5-pro",
      "gemini-2.5-flash",
      "gemini-2.5-flash-lite",
    ],
  },
  {
    id: "xai",
    name: "xAI · Grok",
    group: "国际主流",
    transport: "openai",
    baseUrl: "https://api.x.ai/v1",
    modelHint: "读取当前 xAI API Key 可用的 Grok 模型",
    supportsModelList: true,
  },
  {
    id: "mistral",
    name: "Mistral AI",
    group: "国际主流",
    transport: "openai",
    baseUrl: "https://api.mistral.ai/v1",
    modelHint: "例如 mistral-medium-latest",
    supportsModelList: true,
    fallbackModels: ["mistral-medium-latest", "mistral-small-latest", "mistral-large-latest"],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    group: "中国大陆",
    transport: "openai",
    baseUrl: "https://api.deepseek.com",
    modelHint: "例如 deepseek-v4-flash",
    supportsModelList: true,
    fallbackModels: ["deepseek-v4-flash", "deepseek-v4-pro", "deepseek-v4-flash-vision-exp"],
  },
  {
    id: "qwen-cn",
    name: "阿里云百炼 · Qwen（中国站）",
    group: "中国大陆",
    transport: "openai",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    modelHint: "读取百炼账号当前可用 Qwen 模型",
    supportsModelList: true,
  },
  {
    id: "qwen-intl",
    name: "Alibaba Model Studio · Qwen（国际站）",
    group: "国际主流",
    transport: "openai",
    baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    modelHint: "读取国际站当前可用 Qwen 模型",
    supportsModelList: true,
  },
  {
    id: "kimi",
    name: "Kimi · 月之暗面 Moonshot AI",
    group: "中国大陆",
    transport: "openai",
    baseUrl: "https://api.moonshot.cn/v1",
    modelHint: "读取当前 Kimi / Moonshot 账号可用模型，也可手工输入模型 ID",
    supportsModelList: true,
    fallbackModels: ["kimi-k2.5", "kimi-k2-turbo-preview", "moonshot-v1-128k"],
    note: "Kimi 官方 API，模型以你的账号当前实际可用列表为准。",
  },
  {
    id: "xiaomi-mimo",
    name: "小米 MiMo",
    group: "中国大陆",
    transport: "openai",
    baseUrl: "https://api.xiaomimimo.com/v1",
    modelHint: "例如 mimo-v2.5-pro；可读取账号当前可用模型",
    supportsModelList: true,
    fallbackModels: ["mimo-v2.5-pro", "mimo-v2-pro", "mimo-v2-flash"],
    note: "小米 MiMo 官方 API，兼容 OpenAI Chat Completions；支持文本/部分多模态模型。",
  },
  {
    id: "stepfun",
    name: "阶跃星辰 StepFun",
    group: "中国大陆",
    transport: "openai",
    baseUrl: "https://api.stepfun.com/v1",
    modelHint: "例如 step-3.5-flash；可读取当前账号模型列表",
    supportsModelList: true,
    fallbackModels: ["step-3.5-flash", "step-3.5-flash-2603"],
    note: "官方 OpenAI 兼容接口，支持文本与部分视觉模型。",
  },
  {
    id: "baichuan",
    name: "百川智能 Baichuan",
    group: "中国大陆",
    transport: "openai",
    baseUrl: "https://api.baichuan-ai.com/v1",
    modelHint: "输入百川开放平台当前可用模型 ID",
    supportsModelList: false,
    fallbackModels: ["Baichuan2-Turbo", "Baichuan2-Turbo-192k"],
    note: "百川官方 Chat Completions API。若控制台提供了更新模型 ID，可直接手工输入。",
  },
  {
    id: "spark",
    name: "科大讯飞 · 星火 Spark",
    group: "中国大陆",
    transport: "openai",
    baseUrl: "https://spark-api-open.xf-yun.com/v1",
    modelHint: "输入星火控制台对应模型 ID，例如 generalv3.5",
    supportsModelList: false,
    fallbackModels: ["generalv3.5"],
    note: "使用讯飞控制台 HTTP 服务中的 APIPassword 作为 API Key。",
  },
  {
    id: "sense-nova",
    name: "商汤 · 日日新 SenseNova",
    group: "中国大陆",
    transport: "openai",
    baseUrl: "https://api.sensenova.cn/v1/llm",
    modelHint: "输入 SenseNova 控制台已开通的模型 ID",
    supportsModelList: false,
    note: "使用 SenseNova API Token；该接口路径为 /v1/llm/chat-completions。",
  },
  {
    id: "yi",
    name: "零一万物 · Yi",
    group: "中国大陆",
    transport: "openai",
    baseUrl: "https://api.lingyiwanwu.com/v1",
    modelHint: "例如 Yi-Lightning / Yi-Large / Yi-Vision，以控制台当前可用模型为准",
    supportsModelList: true,
    fallbackModels: ["Yi-Lightning", "Yi-Large", "Yi-Vision"],
    note: "零一万物 OpenAI-Compatible API。",
  },
  {
    id: "360",
    name: "360 智脑开放平台",
    group: "中国大陆",
    transport: "openai",
    baseUrl: "https://api.360.cn/v1",
    modelHint: "可读取 360 智脑账号当前模型列表",
    supportsModelList: true,
    fallbackModels: ["360gpt2-pro", "360gpt-pro"],
    note: "360 智脑官方 OpenAI-Compatible API。",
  },
  {
    id: "minimax",
    name: "MiniMax",
    group: "中国大陆",
    transport: "openai",
    baseUrl: "https://api.minimaxi.com/v1",
    modelHint: "例如 MiniMax-M2.7",
    supportsModelList: true,
    fallbackModels: ["MiniMax-M2.7", "MiniMax-M2.5"],
  },
  {
    id: "zhipu",
    name: "智谱 AI · GLM",
    group: "中国大陆",
    transport: "openai",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    modelHint: "输入或读取当前 GLM 模型 ID",
    supportsModelList: true,
  },
  {
    id: "siliconflow",
    name: "硅基流动 SiliconFlow",
    group: "聚合平台",
    transport: "openai",
    baseUrl: "https://api.siliconflow.cn/v1",
    modelHint: "可读取平台当前上架的 Qwen / DeepSeek / Kimi / GLM 等模型",
    supportsModelList: true,
  },
  {
    id: "openrouter",
    name: "OpenRouter · 数百模型聚合",
    group: "聚合平台",
    transport: "openai",
    baseUrl: "https://openrouter.ai/api/v1",
    modelHint: "可读取 OpenRouter 当前全部文本模型",
    supportsModelList: true,
    note: "覆盖 OpenAI、Claude、Gemini、Grok、Qwen、DeepSeek、Mistral、Meta 等大量模型。",
  },
  {
    id: "groq",
    name: "GroqCloud",
    group: "高速推理",
    transport: "openai",
    baseUrl: "https://api.groq.com/openai/v1",
    modelHint: "读取 GroqCloud 当前生产模型",
    supportsModelList: true,
  },
  {
    id: "together",
    name: "Together AI",
    group: "聚合平台",
    transport: "openai",
    baseUrl: "https://api.together.xyz/v1",
    modelHint: "读取 Together 当前可用模型",
    supportsModelList: true,
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    group: "聚合平台",
    transport: "openai",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    modelHint: "读取 Fireworks 当前可用模型",
    supportsModelList: true,
  },
  {
    id: "cerebras",
    name: "Cerebras Inference",
    group: "高速推理",
    transport: "openai",
    baseUrl: "https://api.cerebras.ai/v1",
    modelHint: "读取 Cerebras 当前可用高速模型",
    supportsModelList: true,
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    group: "聚合平台",
    transport: "openai",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    modelHint: "读取 NVIDIA NIM 当前模型",
    supportsModelList: true,
  },
  {
    id: "doubao",
    name: "火山方舟 · 豆包",
    group: "中国大陆",
    transport: "openai",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    modelHint: "例如 doubao-seed-2-0-lite-260215，或填写你的 Endpoint/Model ID",
    supportsModelList: false,
    fallbackModels: ["doubao-seed-2-0-lite-260215"],
    note: "火山方舟部分账号使用模型 ID / 推理接入点 ID，请以控制台为准。",
  },
  {
    id: "baidu",
    name: "百度千帆 · ERNIE / 第三方模型",
    group: "中国大陆",
    transport: "openai",
    baseUrl: "https://qianfan.baidubce.com/v2",
    modelHint: "输入千帆控制台当前可用模型 ID",
    supportsModelList: true,
  },
  {
    id: "tencent",
    name: "腾讯混元 Hunyuan",
    group: "中国大陆",
    transport: "openai",
    baseUrl: "https://api.hunyuan.cloud.tencent.com/v1",
    modelHint: "例如 hunyuan-turbos-latest",
    supportsModelList: true,
    fallbackModels: ["hunyuan-turbos-latest"],
  },
  {
    id: "perplexity",
    name: "Perplexity API",
    group: "国际主流",
    transport: "openai",
    baseUrl: "https://api.perplexity.ai",
    modelHint: "读取或输入当前可用模型",
    supportsModelList: true,
  },
  {
    id: "custom",
    name: "自定义 OpenAI-Compatible",
    group: "自定义",
    transport: "openai",
    baseUrl: "",
    modelHint: "填写任意兼容 /chat/completions 的 Base URL 与模型 ID",
    supportsModelList: true,
    note: "用于接入未来新平台、公司内网网关、LM Studio、vLLM 等兼容接口。",
  },
];

export function getCloudProviderPreset(id?: string) {
  return CLOUD_PROVIDER_PRESETS.find((p) => p.id === id) || CLOUD_PROVIDER_PRESETS[0];
}
